### ISSUE TITLE
TypeError: subcon should be a Construct field

### ISSUE THREAD

**Issue by eploft** [Flameeyes/glucometerutils#41]
Hi!

I'm trying tu run the glucometerutils under Linux Mint, but I'm getting the following error report:

python3.5 ./glucometer.py --driver fslibre
Traceback (most recent call last):
  File "./glucometer.py", line 7, in <module>
    glucometer.main()
  File "/home/xyz/glucometerutils/glucometerutils/glucometer.py", line 73, in main
    driver = importlib.import_module('glucometerutils.drivers.' + args.driver)
  File "/usr/lib/python3.5/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 986, in _gcd_import
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 665, in exec_module
  File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
  File "/home/xyz/glucometerutils/glucometerutils/drivers/fslibre.py", line 26, in <module>
    from glucometerutils.support import freestyle
  File "/home/xyz/glucometerutils/glucometerutils/support/freestyle.py", line 29, in <module>
    'hid_report' / construct.Const(construct.Byte, 0),
  File "/usr/local/lib/python3.5/dist-packages/construct/core.py", line 2461, in __init__
    super(Const, self).__init__(subcon)
  File "/usr/local/lib/python3.5/dist-packages/construct/core.py", line 562, in __init__
    raise TypeError("subcon should be a Construct field")
TypeError: subcon should be a Construct field

Any ideas? Is it a bug, or I'm doing something wrong?

Installed:
python3.5 -m pip install --upgrade pip
python3.5 -m pip install setuptools
python3.5 -m pip install construct

**Comment by Flameeyes** [comment]
See Issue #38 
The construct APIs are unstable, so you need construct 2.8.22 for this to work for now (the setup.py has the actual versioned requirement).

**Comment by arekbulski** [comment]
Yes, I concur.
