### ISSUE TITLE
need attrs in requirements

### ISSUE THREAD

**Issue by psywhale** [Flameeyes/glucometerutils#52]
without installing attrs common.py will throw errors on the decorators. 
`pip install attrs`

**Comment by moisesStevend** [comment]
I've tried to put :  
>>sudo pip3 install attr  #however It's not correct for our trying

but the correct library was:
>> sudo pip3 install attrs

**Comment by Flameeyes** [comment]
This is in requirements (now?)

**Comment by lahvey** [comment]
pull from commit [610e3197cc97ecdfcadc0c31af6591e72242ff8c](https://github.com/Flameeyes/glucometerutils/commit/610e3197cc97ecdfcadc0c31af6591e72242ff8c)
on Mac 10.14.3
```shell
$ python3 -m venv $(pwd)/glucometerutils-venv
$ . glucometerutils-venv/bin/activate
(glucometerutils-venv) $ DRIVER= fsprecisionneo
(glucometerutils-venv) $ pip install "git+https://github.com/Flameeyes/glucometerutils.git#egg=project[${DRIVER}]"
$ glucometer --driver ${DRIVER} help

Traceback (most recent call last):
  File "/var/apps/glucometerutils/glucometerutils-venv/bin/glucometer", line 11, in <module>
    load_entry_point('glucometerutils==1', 'console_scripts', 'glucometer')()
  File "/var/apps/glucometerutils/glucometerutils-venv/lib/python3.7/site-packages/pkg_resources/__init__.py", line 489, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/var/apps/glucometerutils/glucometerutils-venv/lib/python3.7/site-packages/pkg_resources/__init__.py", line 2793, in load_entry_point
    return ep.load()
  File "/var/apps/glucometerutils/glucometerutils-venv/lib/python3.7/site-packages/pkg_resources/__init__.py", line 2411, in load
    return self.resolve()
  File "/var/apps/glucometerutils/glucometerutils-venv/lib/python3.7/site-packages/pkg_resources/__init__.py", line 2417, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/var/apps/glucometerutils/glucometerutils-venv/lib/python3.7/site-packages/glucometerutils/glucometer.py", line 13, in <module>
    from glucometerutils import common
  File "/var/apps/glucometerutils/glucometerutils-venv/lib/python3.7/site-packages/glucometerutils/common.py", line 15, in <module>
    import attr
```

**Comment by lahvey** [comment]
After `pip install attrs`, it works.
