### ISSUE TITLE
datetime ValueError using 'info'

### ISSUE THREAD

**Issue by matmutant** [Flameeyes/glucometerutils#58]
Hello, I have and issue with a FreeStyle Optium Neo : 'info' output using temporary workaround (see #57 pull request)

### Driver used
DRIVER=fsprecisionneo

### 'info'
```
FreeStyle Precision Neo
Serial Number: LAGV342S03382
Version Information:
    Software version: 1.18 May 21 2015
Native Unit: mg/dL
Time: N/A
```

### Raw output without ValueError exception handling, here is the output:
```
$ glucometer --driver ${DRIVER} infoTraceback (most recent call last):
  File "/home/matmutant/Documents/glucometer/glucometerutils-master/glucometerutils-venv/bin/glucometer", line 11, in <module>
    load_entry_point('glucometerutils==1', 'console_scripts', 'glucometer')()
  File "/home/matmutant/Documents/glucometer/glucometerutils-master/glucometerutils-venv/lib/python3.5/site-packages/glucometerutils/glucometer.py", line 88, in main
    time_str = device.get_datetime()
  File "/home/matmutant/Documents/glucometer/glucometerutils-master/glucometerutils-venv/lib/python3.5/site-packages/glucometerutils/support/freestyle.py", line 203, in get_datetime
    return datetime.datetime(year + 2000, month, day, hour, minute)
ValueError: month must be in 1..12
```

I assume the glucometer does not pass datetime in a valid format.  

### debug info (with ValueError exception handling)
```
$ glucometer --vlog 10 --driver ${DRIVER} info
INFO:root:No --device parameter provided, using hidapi library.
DEBUG:root:Sending packet: b'\x00\x04\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00'
DEBUG:root:Read packet: b'4\x01\r.18 May 21 2015\r\nCKSM:00000391\r\nCMD OK\r\n\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00'
DEBUG:root:Sending packet: b'\x00\x05\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00'
DEBUG:root:Read packet: b'\x06\x1800000000 (No SerialNum)\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00'
DEBUG:root:Sending packet: b'\x00\x15\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00'
DEBUG:root:Read packet: b'5\x111.18 May 21 2015\x00SM:0000032D\r\nCMD OK\r\n\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00'
DEBUG:root:Sending packet: b'\x00\x01\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00'
DEBUG:root:Read packet: b'q\x01\x01.18 May 21 2015\r\nCKSM:00000391\r\nCMD OK\r\n\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00'
DEBUG:root:Sending packet: b'\x00`\t$serlnum?\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00'
DEBUG:root:Read packet: b'`&LAGV342S03382\r\nCKSM:0000032D\r\nCMD OK\r\nK\r\n\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00'
DEBUG:root:Sending packet: b'\x00`\x07$swver?\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00'
DEBUG:root:Read packet: b'"\x01\x030000000 (No SerialNum)\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00'
DEBUG:root:Read packet: b'`)1.18 May 21 2015\r\nCKSM:00000391\r\nCMD OK\r\n\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00'
DEBUG:root:Sending packet: b'\x00`\x06$date?\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00'
DEBUG:root:Read packet: b'`$255,255,255\r\nCKSM:00000243\r\nCMD OK\r\n OK\r\n\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00'
DEBUG:root:Sending packet: b'\x00`\x06$time?\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00'
DEBUG:root:Read packet: b'` 255,255\r\nCKSM:0000017B\r\nCMD OK\r\nD OK\r\n\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00'
FreeStyle Precision Neo
Serial Number: LAGV342S03382
Version Information:
    Software version: 1.18 May 21 2015
Native Unit: mg/dL
Time: N/A
```

### thank you for this  great tool :+1:

**Comment by Flameeyes** [comment]
Okay that's an interesting one. It looks like the device reports 255,255,255 as date and 255,255 as time.

I'll add an explicit error to deal with this, but could you check what the device _itself_ report as date and time? I wonder if it might just be that the battery ran out and the RTC lost any idea of what time it is...

**Comment by matmutant** [comment]
You know what's funny? you are 100% right about "ran out battery"
As I found that device in the recycle bin and just played with it only to dump its content, I did not event try/check to power it at first ... which it doesn't, as there is actually NO battery inside ! (so yeah, the RTC cannot keep time without juice)
gonna look for two CR2032 and give you an update :)

**Comment by matmutant** [comment]
![infoWithBattery](https://user-images.githubusercontent.com/8789889/60495864-ed8b8900-9cb1-11e9-8365-d45f158ccd59.png)

found two CR2032 in my "stuff"
device works fine with batteries in ... and RTC working ! ==> right time is displayed
thank you :)
