### ISSUE TITLE
OSError: [Errno 22] Invalid argument

### ISSUE THREAD

**Issue by kAgotsi** [Flameeyes/glucometerutils#64]
Hello Flameeyes. 
Thank you for your wonderful work.
I want to test your work on ubuntu 19.04 to read the data from a FreeStyle free reader. I installed all the dependencies. 

but when I run   :  `glucometer` --driver fslibre --device /dev/bus/usb/002/003 dump`
I have this traceback : 

Traceback (most recent call last):
  File "/home/kommit/Documents/glucose/glucometerutils-venv/bin/glucometer", line 11, in <module>
    load_entry_point('glucometerutils==1', 'console_scripts', 'glucometer')()
  File "/home/kommit/Documents/glucose/glucometerutils-venv/lib/python3.6/site-packages/glucometerutils/glucometer.py", line 88, in main
    device.connect()
  File "/home/kommit/Documents/glucose/glucometerutils-venv/lib/python3.6/site-packages/glucometerutils/support/freestyle.py", line 103, in connect
    self._read_response()
  File "/home/kommit/Documents/glucose/glucometerutils-venv/lib/python3.6/site-packages/glucometerutils/support/freestyle.py", line 126, in _read_response
    usb_packet = self._read()
  File "/home/kommit/Documents/glucose/glucometerutils-venv/lib/python3.6/site-packages/glucometerutils/support/hiddevice.py", line 96, in _read
    return bytes(self.handle_.read(size))
OSError: [Errno 22] Invalid argument.

Please can I you debug me?
Thanks.

**Comment by kAgotsi** [comment]
I was able to solve this problem by using pip3
