### ISSUE TITLE
glucometer.py alternately Connection error and Invalid response FreeStyle Precision Neo

### ISSUE THREAD

**Issue by sanderisbestok** [Flameeyes/glucometerutils#73]
Trying to get data from the FreeStyle Precision Neo but it doesn't work. I get alternately the following errors when using the command `sudo glucometer --driver fsprecisionneo`:

`glucometerutils.exceptions.InvalidResponse: Invalid response received:
Message type 22 does not match expectations: b'\x03'`

and 

`glucometerutils.exceptions.ConnectionFailed: Connection error: unexpected message 60:0d0a434b534d3a30303030303031370d0a434d44204f4b0d0a
`

**Comment by sanderisbestok** [comment]
So I tried some things, first I had to disable the if message_type != self.TEXT_REPLY_CMD check. 

```
This went wrong on the read patient name:
DEBUG:root:Sending packet: b'\x00`\x08$ptname?\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00'
DEBUG:root:Read packet: b'"\x01\x03.18 May 21 2015\r\nCKSM:00000391\r\nCMD OK\r\n\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00'

```
If I disabled did, it did continue but gave an error on the Checksum, most of the time on the part below, but sometimes also on the one below this one.

If I disabled the checksum test, I got (most of the time, sometimes missing one record) all the data which was on the device.
```
DEBUG:root:Sending packet: b'\x00`\x08$ptname?\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00'
DEBUG:root:Read packet: b'"\x01\x03ander Hansen\r\nCKSM:000004F1\r\nCMD OK\r\n,0,1\r\n\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00'
DEBUG:root:Received message: type 22 content 03
DEBUG:root:Read packet: b'`&Sander Hansen\r\nCKSM:000004F1\r\nCMD OK\r\n,0,0,1\r\n\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00'
DEBUG:root:Received message: type 60 content 53616e6465722048616e73656e0d0a434b534d3a30303030303446310d0a434d44204f4b0d0a
Traceback (most recent call last):
  File "glucometer.py", line 9, in <module>
    glucometer.main()
  File "/home/sander/Documents/forensic/cybercrime/glucometerutils/glucometerutils/glucometer.py", line 89, in main
    device_info = device.get_meter_info()
  File "/home/sander/Documents/forensic/cybercrime/glucometerutils/glucometerutils/drivers/fsprecisionneo.py", line 64, in get_meter_info
    patient_name=self.get_patient_name())
  File "/home/sander/Documents/forensic/cybercrime/glucometerutils/glucometerutils/support/freestyle.py", line 266, in get_patient_name
    patient_name = self._send_text_command(b'$ptname?').rstrip('\r\n')
  File "/home/sander/Documents/forensic/cybercrime/glucometerutils/glucometerutils/support/freestyle.py", line 240, in _send_text_command
    _verify_checksum(message, match.group('checksum'))
  File "/home/sander/Documents/forensic/cybercrime/glucometerutils/glucometerutils/support/freestyle.py", line 105, in _verify_checksum
    raise exceptions.InvalidChecksum(expected_checksum, calculated_checksum)
glucometerutils.exceptions.InvalidChecksum: Invalid response received:
Response checksum not matching: 000004f1 (wire) != 000004f4 (calculated)
```

SECOND CHECKSUM ERROR
```
DEBUG:root:Sending packet: b'\x00`\x07$swver?\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00'
DEBUG:root:Read packet: b'"\x01\x03,00001028\r\nCKSM:00001228\r\nCMD OK\r\nK\r\n\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00'
DEBUG:root:Received message: type 22 content 03
DEBUG:root:Read packet: b'`)1.18 May 21 2015\r\nCKSM:00000391\r\nCMD OK\r\n\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00'
DEBUG:root:Received message: type 60 content 312e3138204d617920323120323031350d0a434b534d3a30303030303339310d0a434d44204f4b0d0a
Traceback (most recent call last):
  File "glucometer.py", line 9, in <module>
    glucometer.main()
  File "/home/sander/Documents/forensic/cybercrime/glucometerutils/glucometerutils/glucometer.py", line 89, in main
    device_info = device.get_meter_info()
  File "/home/sander/Documents/forensic/cybercrime/glucometerutils/glucometerutils/drivers/fsprecisionneo.py", line 62, in get_meter_info
    'Software version: ' + self._get_version(),),
  File "/home/sander/Documents/forensic/cybercrime/glucometerutils/glucometerutils/support/freestyle.py", line 257, in _get_version
    return self._send_text_command(b'$swver?').rstrip('\r\n')
  File "/home/sander/Documents/forensic/cybercrime/glucometerutils/glucometerutils/support/freestyle.py", line 240, in _send_text_command
    _verify_checksum(message, match.group('checksum'))
  File "/home/sander/Documents/forensic/cybercrime/glucometerutils/glucometerutils/support/freestyle.py", line 105, in _verify_checksum
    raise exceptions.InvalidChecksum(expected_checksum, calculated_checksum)
glucometerutils.exceptions.InvalidChecksum: Invalid response received:
Response checksum not matching: 00000391 (wire) != 00000394 (calculated)
```

**Comment by Flameeyes** [comment]
Yeah this was me breaking stuff when trying to get the Libre working better. This should now be fixed. Thank you for reporting it!
